/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TrackController;
import javax.swing.JOptionPane;
import model.TrackDAO;

/**
 *
 * @author Aluno
 */
public class JAdd extends javax.swing.JFrame {

    private TrackController trackController;

    /**
     * Creates new form JAddUpdate
     */
    public JAdd(TrackController trackController) {
        this.trackController = trackController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnTrackAdd = new javax.swing.JButton();
        txtTrackTitle = new javax.swing.JTextField();
        txtTrackLength = new javax.swing.JTextField();
        txtTrackArtistName = new javax.swing.JTextField();
        txtTrackReleaseTitle = new javax.swing.JTextField();
        txtTrackAudioFilePath = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTrackCoverImagePath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(10, 10, 10));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Title");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Length");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Artist Name");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Release Title");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Audio File Path");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        btnTrackAdd.setBackground(new java.awt.Color(55, 55, 55));
        btnTrackAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnTrackAdd.setText("Add");
        btnTrackAdd.setFocusable(false);
        btnTrackAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrackAddMouseClicked(evt);
            }
        });
        jPanel1.add(btnTrackAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 125, -1));

        txtTrackTitle.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.add(txtTrackTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, 28));

        txtTrackLength.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackLength.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackLength.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.add(txtTrackLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 150, 28));

        txtTrackArtistName.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackArtistName.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackArtistName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.add(txtTrackArtistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 85, 28));

        txtTrackReleaseTitle.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackReleaseTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackReleaseTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.add(txtTrackReleaseTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 85, 28));

        txtTrackAudioFilePath.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackAudioFilePath.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackAudioFilePath.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.add(txtTrackAudioFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 415, 28));

        jLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("ADD TRACK");
        jLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 130, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Cover Image Path");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        txtTrackCoverImagePath.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackCoverImagePath.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackCoverImagePath.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.add(txtTrackCoverImagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 415, 28));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrackAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrackAddMouseClicked
        String title = txtTrackTitle.getText();
        String releaseTitle = txtTrackReleaseTitle.getText();
        String artistName = txtTrackArtistName.getText();
        String length = txtTrackLength.getText();
        String audioPath = txtTrackAudioFilePath.getText();
        String coverImagePath = txtTrackCoverImagePath.getText();
        trackController.add(title, releaseTitle, artistName, length, audioPath, coverImagePath);

        JOptionPane.showMessageDialog(this, "Música salva!");
        txtTrackTitle.setText("");
        txtTrackReleaseTitle.setText("");
        txtTrackArtistName.setText("");
        txtTrackLength.setText("");
        txtTrackAudioFilePath.setText("");
        txtTrackCoverImagePath.setText("");
    }//GEN-LAST:event_btnTrackAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrackDAO trackDAO = new TrackDAO();
                TrackController trackController = new TrackController(trackDAO);

                JAdd jadd = new JAdd(trackController);
                jadd.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTrackAdd;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTrackArtistName;
    private javax.swing.JTextField txtTrackAudioFilePath;
    private javax.swing.JTextField txtTrackCoverImagePath;
    private javax.swing.JTextField txtTrackLength;
    private javax.swing.JTextField txtTrackReleaseTitle;
    private javax.swing.JTextField txtTrackTitle;
    // End of variables declaration//GEN-END:variables
}
