/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TrackController;
import data.Track;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.TrackDAO;

/**
 *
 * @author Aluno
 */
public class JDelete extends javax.swing.JFrame {
    
    private TrackController trackController;

    /**
     * Creates new form JDelete
     */
    public JDelete(TrackController trackController) {
        this.trackController = trackController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTrackDeleteID = new javax.swing.JTextField();
        btnTrackDelete = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tblTrack = new javax.swing.JTable();
        btnTrackSearchID = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 10, 10));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        txtTrackDeleteID.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackDeleteID.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackDeleteID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txtTrackDeleteID.setPreferredSize(new java.awt.Dimension(70, 26));
        jPanel1.add(txtTrackDeleteID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        btnTrackDelete.setBackground(new java.awt.Color(55, 55, 55));
        btnTrackDelete.setText("Remove");
        btnTrackDelete.setFocusable(false);
        btnTrackDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrackDeleteMouseClicked(evt);
            }
        });
        jPanel1.add(btnTrackDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        tblTrack.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title", "Length", "Audio Path", "Artist ID", "Release ID"
            }
        ));
        jScrollPane.setViewportView(tblTrack);

        jPanel1.add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 315, 155));

        btnTrackSearchID.setBackground(new java.awt.Color(55, 55, 55));
        btnTrackSearchID.setText("Search ID");
        btnTrackSearchID.setFocusable(false);
        btnTrackSearchID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrackSearchIDMouseClicked(evt);
            }
        });
        jPanel1.add(btnTrackSearchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        jLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("REMOVE TRACK");
        jLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrackDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrackDeleteMouseClicked
        int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir essa música?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(resposta == JOptionPane.YES_OPTION) {
            int id = Integer.valueOf(txtTrackDeleteID.getText());
            if(trackController.delete(id)) {
                JOptionPane.showMessageDialog(this, "Música excluída!");
                fillTable(trackController.getById(id));
            }else{
                JOptionPane.showMessageDialog(this, "ID não encontrado!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Tome mais cuidado na próxima vez!");
        }
        txtTrackDeleteID.setText("");
    }//GEN-LAST:event_btnTrackDeleteMouseClicked

    private void btnTrackSearchIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrackSearchIDMouseClicked
        int id = Integer.valueOf(txtTrackDeleteID.getText());
        fillTable(trackController.getById(id));
//        txtTrackDeleteID.setText("");
    }//GEN-LAST:event_btnTrackSearchIDMouseClicked
    
    public void fillTable(ArrayList<Track> track) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Title");
        model.addColumn("Release");
        model.addColumn("Artist");
        model.addColumn("Length");
        model.addColumn("Audio File");
        model.addColumn("Cover Image Path");

        for (Track t : track) {
            model.addRow(new Object[]{t.getId(), t.getTitle(), t.getReleaseTitle(), t.getArtistName(), t.getTrackLength(), t.getAudioFile(), t.getCoverImagePath()});
        }
        tblTrack.setModel(model);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrackDAO trackDAO = new TrackDAO();
                TrackController trackController = new TrackController(trackDAO);
                
                JDelete jdelete = new JDelete(trackController);
                jdelete.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTrackDelete;
    private javax.swing.JButton btnTrackSearchID;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable tblTrack;
    private javax.swing.JTextField txtTrackDeleteID;
    // End of variables declaration//GEN-END:variables
}
