/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TrackController;
import data.Track;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.TrackDAO;

/**
 *
 * @author Aluno
 */
public class JUpdate extends javax.swing.JFrame {

    private TrackController trackController;

    /**
     * Creates new form JAddUpdate
     */
    public JUpdate(TrackController trackController) {
        this.trackController = trackController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnTrackUpdateAll = new javax.swing.JButton();
        txtTrackTitle = new javax.swing.JTextField();
        txtTrackLength = new javax.swing.JTextField();
        txtTrackArtistName = new javax.swing.JTextField();
        txtTrackReleaseTitle = new javax.swing.JTextField();
        txtTrackAudioFilePath = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtTrackSearchID = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTrack = new javax.swing.JTable();
        btnTrackSearchID = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        txtTrackCoverImagePath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(10, 10, 10));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Title");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Length");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Artist Name");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Release Title");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Audio File Path");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        btnTrackUpdateAll.setBackground(new java.awt.Color(55, 55, 55));
        btnTrackUpdateAll.setForeground(new java.awt.Color(255, 255, 255));
        btnTrackUpdateAll.setText("Update All");
        btnTrackUpdateAll.setFocusable(false);
        btnTrackUpdateAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrackUpdateAllMouseClicked(evt);
            }
        });
        jPanel1.add(btnTrackUpdateAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 125, -1));

        txtTrackTitle.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.add(txtTrackTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 150, 28));

        txtTrackLength.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackLength.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackLength.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.add(txtTrackLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 150, 28));

        txtTrackArtistName.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackArtistName.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackArtistName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.add(txtTrackArtistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 85, 28));

        txtTrackReleaseTitle.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackReleaseTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackReleaseTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.add(txtTrackReleaseTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 85, 28));

        txtTrackAudioFilePath.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackAudioFilePath.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackAudioFilePath.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.add(txtTrackAudioFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 415, 28));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("ID");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        txtTrackSearchID.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackSearchID.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackSearchID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txtTrackSearchID.setPreferredSize(new java.awt.Dimension(70, 26));
        jPanel1.add(txtTrackSearchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        tblTrack.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title", "Length", "Audio Path", "Artist ID", "Release ID"
            }
        ));
        jScrollPane5.setViewportView(tblTrack);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 550, 155));

        btnTrackSearchID.setBackground(new java.awt.Color(55, 55, 55));
        btnTrackSearchID.setText("Search ID");
        btnTrackSearchID.setFocusable(false);
        btnTrackSearchID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrackSearchIDMouseClicked(evt);
            }
        });
        jPanel1.add(btnTrackSearchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Cover Image Path");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        txtTrackCoverImagePath.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackCoverImagePath.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackCoverImagePath.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.add(txtTrackCoverImagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 415, 28));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPDATE TRACK");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 13, 10, 10));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrackUpdateAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrackUpdateAllMouseClicked
        int id = Integer.valueOf(txtTrackSearchID.getText());
        String title = txtTrackTitle.getText();
        String releaseTitle = txtTrackReleaseTitle.getText();
        String artistName = txtTrackArtistName.getText();
        String length = txtTrackLength.getText();
        String audioPath = txtTrackAudioFilePath.getText();
        String coverImagePath = txtTrackCoverImagePath.getText();

        if (trackController.updateAll(id, title, releaseTitle, artistName, length, audioPath, coverImagePath)) {
            JOptionPane.showMessageDialog(this, "Música atualizada!");
            fillTable(trackController.getById(id));
        } else {
            JOptionPane.showMessageDialog(this, "ID não encontrado!");
        }
    }//GEN-LAST:event_btnTrackUpdateAllMouseClicked

    private void btnTrackSearchIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrackSearchIDMouseClicked
        int id = Integer.valueOf(txtTrackSearchID.getText());
        fillTable(trackController.getById(id));
    }//GEN-LAST:event_btnTrackSearchIDMouseClicked

    public void fillTable(ArrayList<Track> track) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Title");
        model.addColumn("Release");
        model.addColumn("Artist");
        model.addColumn("Length");
        model.addColumn("Audio File");
        model.addColumn("Cover Image Path");

        for (Track t : track) {
            model.addRow(new Object[]{t.getId(), t.getTitle(), t.getReleaseTitle(), t.getArtistName(), t.getTrackLength(), t.getAudioFile(), t.getCoverImagePath()});
        }
        tblTrack.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrackDAO trackDAO = new TrackDAO();
                TrackController trackController = new TrackController(trackDAO);

                JUpdate jupdate = new JUpdate(trackController);
                jupdate.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTrackSearchID;
    private javax.swing.JButton btnTrackUpdateAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblTrack;
    private javax.swing.JTextField txtTrackArtistName;
    private javax.swing.JTextField txtTrackAudioFilePath;
    private javax.swing.JTextField txtTrackCoverImagePath;
    private javax.swing.JTextField txtTrackLength;
    private javax.swing.JTextField txtTrackReleaseTitle;
    private javax.swing.JTextField txtTrackSearchID;
    private javax.swing.JTextField txtTrackTitle;
    // End of variables declaration//GEN-END:variables
}
