/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Aluno
 */
public class JUpdate extends javax.swing.JFrame {

    /**
     * Creates new form JAddUpdate
     */
    public JUpdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabArtist = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtArtistName = new javax.swing.JTextField();
        txtArtistGenre = new javax.swing.JTextField();
        txtArtistAvatarPath = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArtistAbout = new javax.swing.JTextArea();
        btnArtistUpdateAll = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtArtistDeleteID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnArtistSearchID = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtReleaseTitle = new javax.swing.JTextField();
        txtReleaseLength = new javax.swing.JTextField();
        txtReleaseDate = new javax.swing.JTextField();
        txtReleaseArtistID = new javax.swing.JTextField();
        txtReleaseTrackNumber = new javax.swing.JTextField();
        txtReleaseImagePath = new javax.swing.JTextField();
        btnReleaseUpdateAll = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtReleaseDeleteID = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnReleaseSearchID = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnTrackUpdateAll = new javax.swing.JButton();
        txtTrackTitle = new javax.swing.JTextField();
        txtTrackLength = new javax.swing.JTextField();
        txtTrackArtistID = new javax.swing.JTextField();
        TxtTrackReleaseID = new javax.swing.JTextField();
        txtTrackAudioFilePath = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtArtistDeleteID2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnTrackSearchID = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        tabArtist.setBackground(new java.awt.Color(51, 51, 51));
        tabArtist.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabArtist.setToolTipText("");
        tabArtist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(10, 10, 10));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Genre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("About");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Avatar Image Path");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        txtArtistName.setBackground(new java.awt.Color(51, 51, 51));
        txtArtistName.setForeground(new java.awt.Color(255, 255, 255));
        txtArtistName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(txtArtistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 149, 28));

        txtArtistGenre.setBackground(new java.awt.Color(51, 51, 51));
        txtArtistGenre.setForeground(new java.awt.Color(255, 255, 255));
        txtArtistGenre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(txtArtistGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 150, 28));

        txtArtistAvatarPath.setBackground(new java.awt.Color(51, 51, 51));
        txtArtistAvatarPath.setForeground(new java.awt.Color(255, 255, 255));
        txtArtistAvatarPath.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(txtArtistAvatarPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 450, 28));

        txtArtistAbout.setBackground(new java.awt.Color(51, 51, 51));
        txtArtistAbout.setColumns(20);
        txtArtistAbout.setForeground(new java.awt.Color(255, 255, 255));
        txtArtistAbout.setRows(5);
        txtArtistAbout.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txtArtistAbout.setCaretColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(txtArtistAbout);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 450, 120));

        btnArtistUpdateAll.setBackground(new java.awt.Color(55, 55, 55));
        btnArtistUpdateAll.setForeground(new java.awt.Color(255, 255, 255));
        btnArtistUpdateAll.setText("Update All");
        btnArtistUpdateAll.setFocusable(false);
        jPanel2.add(btnArtistUpdateAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 125, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        txtArtistDeleteID.setBackground(new java.awt.Color(51, 51, 51));
        txtArtistDeleteID.setForeground(new java.awt.Color(255, 255, 255));
        txtArtistDeleteID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txtArtistDeleteID.setPreferredSize(new java.awt.Dimension(70, 26));
        jPanel2.add(txtArtistDeleteID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Genre", "About", "Avatar Path"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 480, 550, 155));

        btnArtistSearchID.setBackground(new java.awt.Color(55, 55, 55));
        btnArtistSearchID.setText("Search ID");
        btnArtistSearchID.setFocusable(false);
        jPanel2.add(btnArtistSearchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        tabArtist.addTab("Artist", jPanel2);

        jPanel3.setBackground(new java.awt.Color(10, 10, 10));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Title");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Length");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Release Date");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Artist ID");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Track Number");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cover Image Path");
        jLabel12.setToolTipText("");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        txtReleaseTitle.setBackground(new java.awt.Color(51, 51, 51));
        txtReleaseTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtReleaseTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.add(txtReleaseTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 150, 28));

        txtReleaseLength.setBackground(new java.awt.Color(51, 51, 51));
        txtReleaseLength.setForeground(new java.awt.Color(255, 255, 255));
        txtReleaseLength.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.add(txtReleaseLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 161, 28));

        txtReleaseDate.setBackground(new java.awt.Color(51, 51, 51));
        txtReleaseDate.setForeground(new java.awt.Color(255, 255, 255));
        txtReleaseDate.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.add(txtReleaseDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 150, 28));

        txtReleaseArtistID.setBackground(new java.awt.Color(51, 51, 51));
        txtReleaseArtistID.setForeground(new java.awt.Color(255, 255, 255));
        txtReleaseArtistID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txtReleaseArtistID.setMinimumSize(new java.awt.Dimension(60, 26));
        jPanel3.add(txtReleaseArtistID, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 70, 28));

        txtReleaseTrackNumber.setBackground(new java.awt.Color(51, 51, 51));
        txtReleaseTrackNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtReleaseTrackNumber.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.add(txtReleaseTrackNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 70, 28));

        txtReleaseImagePath.setBackground(new java.awt.Color(51, 51, 51));
        txtReleaseImagePath.setForeground(new java.awt.Color(255, 255, 255));
        txtReleaseImagePath.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.add(txtReleaseImagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 430, 28));

        btnReleaseUpdateAll.setBackground(new java.awt.Color(55, 55, 55));
        btnReleaseUpdateAll.setForeground(new java.awt.Color(255, 255, 255));
        btnReleaseUpdateAll.setText("Update All");
        btnReleaseUpdateAll.setFocusable(false);
        jPanel3.add(btnReleaseUpdateAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 125, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        txtReleaseDeleteID.setBackground(new java.awt.Color(51, 51, 51));
        txtReleaseDeleteID.setForeground(new java.awt.Color(255, 255, 255));
        txtReleaseDeleteID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txtReleaseDeleteID.setPreferredSize(new java.awt.Dimension(70, 26));
        jPanel3.add(txtReleaseDeleteID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title", "Release Date", "TrackNumber", "Length", "Image Path", "Artist ID"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane3.setViewportView(jTable2);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 480, 550, 155));

        btnReleaseSearchID.setBackground(new java.awt.Color(55, 55, 55));
        btnReleaseSearchID.setText("Search ID");
        btnReleaseSearchID.setFocusable(false);
        jPanel3.add(btnReleaseSearchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        tabArtist.addTab("Release", jPanel3);

        jPanel4.setBackground(new java.awt.Color(10, 10, 10));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Title");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Length");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Artist ID");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Release ID");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Audio File Path");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        btnTrackUpdateAll.setBackground(new java.awt.Color(55, 55, 55));
        btnTrackUpdateAll.setForeground(new java.awt.Color(255, 255, 255));
        btnTrackUpdateAll.setText("Update All");
        btnTrackUpdateAll.setFocusable(false);
        jPanel4.add(btnTrackUpdateAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 125, -1));

        txtTrackTitle.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel4.add(txtTrackTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 150, 28));

        txtTrackLength.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackLength.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackLength.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel4.add(txtTrackLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 150, 28));

        txtTrackArtistID.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackArtistID.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackArtistID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel4.add(txtTrackArtistID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 85, 28));

        TxtTrackReleaseID.setBackground(new java.awt.Color(51, 51, 51));
        TxtTrackReleaseID.setForeground(new java.awt.Color(255, 255, 255));
        TxtTrackReleaseID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel4.add(TxtTrackReleaseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 85, 28));

        txtTrackAudioFilePath.setBackground(new java.awt.Color(51, 51, 51));
        txtTrackAudioFilePath.setForeground(new java.awt.Color(255, 255, 255));
        txtTrackAudioFilePath.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel4.add(txtTrackAudioFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 415, 28));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ID");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        txtArtistDeleteID2.setBackground(new java.awt.Color(51, 51, 51));
        txtArtistDeleteID2.setForeground(new java.awt.Color(255, 255, 255));
        txtArtistDeleteID2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txtArtistDeleteID2.setPreferredSize(new java.awt.Dimension(70, 26));
        jPanel4.add(txtArtistDeleteID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title", "Length", "Audio Path", "Artist ID", "Release ID"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 480, 550, 155));

        btnTrackSearchID.setBackground(new java.awt.Color(55, 55, 55));
        btnTrackSearchID.setText("Search ID");
        btnTrackSearchID.setFocusable(false);
        jPanel4.add(btnTrackSearchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        tabArtist.addTab("Track", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabArtist)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabArtist)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtTrackReleaseID;
    private javax.swing.JButton btnArtistSearchID;
    private javax.swing.JButton btnArtistUpdateAll;
    private javax.swing.JButton btnReleaseSearchID;
    private javax.swing.JButton btnReleaseUpdateAll;
    private javax.swing.JButton btnTrackSearchID;
    private javax.swing.JButton btnTrackUpdateAll;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTabbedPane tabArtist;
    private javax.swing.JTextArea txtArtistAbout;
    private javax.swing.JTextField txtArtistAvatarPath;
    private javax.swing.JTextField txtArtistDeleteID;
    private javax.swing.JTextField txtArtistDeleteID2;
    private javax.swing.JTextField txtArtistGenre;
    private javax.swing.JTextField txtArtistName;
    private javax.swing.JTextField txtReleaseArtistID;
    private javax.swing.JTextField txtReleaseDate;
    private javax.swing.JTextField txtReleaseDeleteID;
    private javax.swing.JTextField txtReleaseImagePath;
    private javax.swing.JTextField txtReleaseLength;
    private javax.swing.JTextField txtReleaseTitle;
    private javax.swing.JTextField txtReleaseTrackNumber;
    private javax.swing.JTextField txtTrackArtistID;
    private javax.swing.JTextField txtTrackAudioFilePath;
    private javax.swing.JTextField txtTrackLength;
    private javax.swing.JTextField txtTrackTitle;
    // End of variables declaration//GEN-END:variables
}
